sudo: false
jdk: oraclejdk8
language: scala

scala:
   - 2.11.12
   - 2.12.6

matrix:
   include:
      - env: PLAY_VERSION=2.5.19
        scala: 2.11.12

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues
